### ISSUE TITLE
azure stuck on 'waiting for device'

### ISSUE THREAD

**Issue by john-honovich** [ipvideomarketinfo/ai-model-tester#37]
been waiting for 5 minutes or more
<img width="812" alt="screen shot 2019-02-24 at 6 49 33 pm" src="https://user-images.githubusercontent.com/8518367/53308220-0815a780-3865-11e9-91c6-481d89a72cd0.png">

**Comment by john-honovich** [comment]
i uploaded a 4K clip successfully but now I am trying to run a model on it and it's back to hanging at 'waiting for available device'
<img width="788" alt="screen shot 2019-02-24 at 6 58 15 pm" src="https://user-images.githubusercontent.com/8518367/53308377-3b0c6b00-3866-11e9-9c82-e9a2e60bde38.png">

maybe the whole AI tester is down, not sure?

**Comment by lefnire** [comment]
Looks like the AWS RDS server just restarted.. maintenance update? I'll see why it does that & how to mitigate. Restarted servers in meantime, back up

**Comment by john-honovich** [comment]
great working now
close this after you find a way to handle RDS server restarts thanks

**Comment by lefnire** [comment]
For my reference:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "server/jobs.py", line 365, in <module>
    check_jobs(args.devices)
  File "server/jobs.py", line 322, in check_jobs
    conn = engine.connect()
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2102, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
    self.pool.unique_connection, _connection)
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 342, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 534, in checkout
    rec._checkin_failed(err)
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 531, in checkout
    dbapi_connection = rec.get_connection()
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 627, in get_connection
    self.__connect()
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/lefnire/anaconda3/envs/py3/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
        Is the server running on host "ipvm-models-rds.c6jlf3eqiikq.us-east-1.rds.amazonaws.com" (3.82.131.7) and accepting
        TCP/IP connections on port 5432?
 (Background on this error at: http://sqlalche.me/e/e3q8)
```
